name: Deploy
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        - name: prepare a secrets
        env:
          AUTH0_AUDIENCE: ${{AUTH0_AUDIENCE}}
          AUTH0_DOMAIN: ${{AUTH0_DOMAIN}}
          LINKED_IN_CONSUMER_KEY: ${{LINKED_IN_CONSUMER_KEY}}
          LINKED_IN_CONSUMER_SECRET: ${{LINKED_IN_CONSUMER_SECRET}}
          MONGO_DB_NAME: ${{MONGO_DB_NAME}}
          MONGO_DB_PASS: ${{MONGO_DB_PASS}}
          MONGO_DB_USERNAME: ${{MONGO_DB_USERNAME}}
        run: python credentialConfigurator.py
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}